org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=true
gradle.cache.push=false

mod_name=Clayworks
mod_id=clayworks
mod_version=4.0.3
mc_version=1.21.1

modrinth_id=1iicrEO3
curseforge_id=592162

neoforge=21.1.160
parchment=2024.11.17
blueprint=8.1.0
jei=19.21.0.247

gallery=2.0.0