package com.teamabnormals.clayworks.core.other;

import com.teamabnormals.clayworks.core.registry.ClayworksBlocks;
import net.minecraft.data.BlockFamily;

import static com.teamabnormals.clayworks.core.registry.ClayworksBlocks.*;

public class ClayworksBlockFamilies {
	public static final BlockFamily TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.TERRACOTTA_BRICKS.get()).slab(TERRACOTTA_BRICK_SLAB.get()).stairs(TERRACOTTA_BRICK_STAIRS.get()).wall(TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_TERRACOTTA_BRICKS.get()).getFamily();

	public static final BlockFamily WHITE_TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.WHITE_TERRACOTTA_BRICKS.get()).slab(WHITE_TERRACOTTA_BRICK_SLAB.get()).stairs(WHITE_TERRACOTTA_BRICK_STAIRS.get()).wall(WHITE_TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_WHITE_TERRACOTTA_BRICKS.get()).getFamily();
	public static final BlockFamily ORANGE_TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.ORANGE_TERRACOTTA_BRICKS.get()).slab(ORANGE_TERRACOTTA_BRICK_SLAB.get()).stairs(ORANGE_TERRACOTTA_BRICK_STAIRS.get()).wall(ORANGE_TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_ORANGE_TERRACOTTA_BRICKS.get()).getFamily();
	public static final BlockFamily MAGENTA_TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.MAGENTA_TERRACOTTA_BRICKS.get()).slab(MAGENTA_TERRACOTTA_BRICK_SLAB.get()).stairs(MAGENTA_TERRACOTTA_BRICK_STAIRS.get()).wall(MAGENTA_TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_MAGENTA_TERRACOTTA_BRICKS.get()).getFamily();
	public static final BlockFamily LIGHT_BLUE_TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.LIGHT_BLUE_TERRACOTTA_BRICKS.get()).slab(LIGHT_BLUE_TERRACOTTA_BRICK_SLAB.get()).stairs(LIGHT_BLUE_TERRACOTTA_BRICK_STAIRS.get()).wall(LIGHT_BLUE_TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_LIGHT_BLUE_TERRACOTTA_BRICKS.get()).getFamily();
	public static final BlockFamily YELLOW_TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.YELLOW_TERRACOTTA_BRICKS.get()).slab(YELLOW_TERRACOTTA_BRICK_SLAB.get()).stairs(YELLOW_TERRACOTTA_BRICK_STAIRS.get()).wall(YELLOW_TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_YELLOW_TERRACOTTA_BRICKS.get()).getFamily();
	public static final BlockFamily LIME_TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.LIME_TERRACOTTA_BRICKS.get()).slab(LIME_TERRACOTTA_BRICK_SLAB.get()).stairs(LIME_TERRACOTTA_BRICK_STAIRS.get()).wall(LIME_TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_LIME_TERRACOTTA_BRICKS.get()).getFamily();
	public static final BlockFamily PINK_TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.PINK_TERRACOTTA_BRICKS.get()).slab(PINK_TERRACOTTA_BRICK_SLAB.get()).stairs(PINK_TERRACOTTA_BRICK_STAIRS.get()).wall(PINK_TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_PINK_TERRACOTTA_BRICKS.get()).getFamily();
	public static final BlockFamily GRAY_TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.GRAY_TERRACOTTA_BRICKS.get()).slab(GRAY_TERRACOTTA_BRICK_SLAB.get()).stairs(GRAY_TERRACOTTA_BRICK_STAIRS.get()).wall(GRAY_TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_GRAY_TERRACOTTA_BRICKS.get()).getFamily();
	public static final BlockFamily LIGHT_GRAY_TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.LIGHT_GRAY_TERRACOTTA_BRICKS.get()).slab(LIGHT_GRAY_TERRACOTTA_BRICK_SLAB.get()).stairs(LIGHT_GRAY_TERRACOTTA_BRICK_STAIRS.get()).wall(LIGHT_GRAY_TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_LIGHT_GRAY_TERRACOTTA_BRICKS.get()).getFamily();
	public static final BlockFamily CYAN_TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.CYAN_TERRACOTTA_BRICKS.get()).slab(CYAN_TERRACOTTA_BRICK_SLAB.get()).stairs(CYAN_TERRACOTTA_BRICK_STAIRS.get()).wall(CYAN_TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_CYAN_TERRACOTTA_BRICKS.get()).getFamily();
	public static final BlockFamily PURPLE_TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.PURPLE_TERRACOTTA_BRICKS.get()).slab(PURPLE_TERRACOTTA_BRICK_SLAB.get()).stairs(PURPLE_TERRACOTTA_BRICK_STAIRS.get()).wall(PURPLE_TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_PURPLE_TERRACOTTA_BRICKS.get()).getFamily();
	public static final BlockFamily BLUE_TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.BLUE_TERRACOTTA_BRICKS.get()).slab(BLUE_TERRACOTTA_BRICK_SLAB.get()).stairs(BLUE_TERRACOTTA_BRICK_STAIRS.get()).wall(BLUE_TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_BLUE_TERRACOTTA_BRICKS.get()).getFamily();
	public static final BlockFamily BROWN_TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.BROWN_TERRACOTTA_BRICKS.get()).slab(BROWN_TERRACOTTA_BRICK_SLAB.get()).stairs(BROWN_TERRACOTTA_BRICK_STAIRS.get()).wall(BROWN_TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_BROWN_TERRACOTTA_BRICKS.get()).getFamily();
	public static final BlockFamily GREEN_TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.GREEN_TERRACOTTA_BRICKS.get()).slab(GREEN_TERRACOTTA_BRICK_SLAB.get()).stairs(GREEN_TERRACOTTA_BRICK_STAIRS.get()).wall(GREEN_TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_GREEN_TERRACOTTA_BRICKS.get()).getFamily();
	public static final BlockFamily RED_TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.RED_TERRACOTTA_BRICKS.get()).slab(RED_TERRACOTTA_BRICK_SLAB.get()).stairs(RED_TERRACOTTA_BRICK_STAIRS.get()).wall(RED_TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_RED_TERRACOTTA_BRICKS.get()).getFamily();
	public static final BlockFamily BLACK_TERRACOTTA_BRICKS = new BlockFamily.Builder(ClayworksBlocks.BLACK_TERRACOTTA_BRICKS.get()).slab(BLACK_TERRACOTTA_BRICK_SLAB.get()).stairs(BLACK_TERRACOTTA_BRICK_STAIRS.get()).wall(BLACK_TERRACOTTA_BRICK_WALL.get()).chiseled(CHISELED_BLACK_TERRACOTTA_BRICKS.get()).getFamily();
}
